### ISSUE TITLE
Release version should be picked from the parent pom directly

### ISSUE THREAD

**Issue by pulasthi7** [wso2/wso2-jenkins-m2release-plugin#3]
In case of version bumps, the build has to be manually stopped, a snapshot build should be triggered to update jenkin's model, and then do another commit to trigger the release build.

**Comment by kasunbg** [comment]
Fixed with https://github.com/wso2/wso2-jenkins-m2release-plugin/commit/81b60ec562252e88841b8e15bd18f2a803425a5a

Thanks @pulasthi7 for reporting the issue.
